### ISSUE TITLE
App Needs Authentication

### ISSUE THREAD

**Issue by jchikwanda** [jchikwanda/scrape-mate-frontend#1]
### Tasks

- [ ] Create Login Form
- [ ] Create Registration Form
- [ ] Create Forgot Password Form
- [ ] Create Verify & Pending Email Verification Page
- [ ] Implement Logic to handle authentication with supabase
- [ ] Create protected routes for authenticated users
